name: CI/CD pipeline
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    concurrency: test
    environment: test
    strategy:
      matrix:
        node-version: [16]

    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'

        - run: npm ci --legacy-peer-deps
        - run: npm run build --if-present
        - run: npm run lint
        - name: run  tests
          run: npm run test
    
